language: php

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

branches:
  except:
    - 0.4

sudo: true


php:
  - 7.0
  - 5.6

env:
  global:
    - ES_VERSION="master"
    - TEST_BUILD_REF="origin/master"
    - ES_TEST_HOST=http://localhost:9200
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"

before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - ./travis/download_and_run_es.sh

before_script:
  - composer install -n
  - sleep 10

script:
  - vendor/bin/phpunit

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
