language: php

sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer


php:
  - 7.0
  - 5.6

env:
  global:
    - WAIT_FOR_ES=1
  matrix:
    - ES_VERSION=2.0.1
    - ES_VERSION=2.1.2
    - ES_VERSION=2.2.1

install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp

before_script:
  - composer install -n
  - sleep 10
  - curl http://127.0.0.1:9200/

script:
  - vendor/bin/phpunit

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
