language: php

sudo: false
services:
  - elasticsearch

php:
  - 7.0
  - 5.6

before_script:
  - composer install -n
  - sleep 10
  - curl http://localhost:9200/

script:
  - vendor/bin/phpunit

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
