language: php

sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer


php:
  - 7.0
  - 5.6

env:
  global:
    - WAIT_FOR_ES=1
  matrix:
    - ES_VERSION=1.7.5
    - ES_VERSION=2.3.3

install:
  - mkdir /tmp/elasticsearch
  - if [ $ES_VERSION = '1.7.5' ]; then wget -O - https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1; fi
  - if [ $ES_VERSION = '2.3.3' ]; then wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1; fi
  - /tmp/elasticsearch/bin/elasticsearch -d --path.data /tmp

before_script:
  - composer install -n
  - sleep 10
  - curl http://127.0.0.1:9200/

script:
  - vendor/bin/phpunit

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - php vendor/bin/codacycoverage clover coverage.clover