language: php


php:
  - 7.0
  - 5.6

before_script:
  - wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb https://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
  - sudo apt-get update && sudo apt-get install elasticsearch
  - sudo update-rc.d elasticsearch defaults 95 10
  - composer install -n
  - sleep 10
  - sudo service elasticsearch restart
  - curl http://localhost:9200/

script:
  - vendor/bin/phpunit

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi
